name: Build and Deploy
on: 
  push:
    branches:
       - main 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: Kendrick-Song/kendrick-song.github.io
        TARGET_BRANCH: deploy
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist
        COMMIT_MESSAGE:  Auto deploy by the vuepress-deploy
        GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
        TZ: 'Asia/Shanghai'
