name: Build and Deploy

on: 
  push:
    branches:
       - main
       
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # 拉取代码
    - name: Checkout
      uses: actions/checkout@master
      with:
#         persist-credentials: false
        fetch-depth: 0
        
    # 生成静态文件
    - name: Build
      run: yarn && yarn docs:build
      env:
        NODE_OPTIONS: --openssl-legacy-provider
    
    # 部署到 GitHub Pages
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 也就是我们刚才生成的 secret
        BRANCH: gh-pages # 部署到 gh-pages 分支，因为 main 分支存放的一般是源码，而 gh-pages 分支则用来存放生成的静态文件
        FOLDER: docs/.vuepress/dist # vuepress 生成的静态文件存放的地方

#     - name: vuepress-deploy
#       uses: jenkey2011/vuepress-deploy@master
#       env:
#         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#         TARGET_REPO: Kendrick-Song/kendrick-song.github.io
#         TARGET_BRANCH: deploy
#         BUILD_SCRIPT: yarn && yarn docs:build
#         BUILD_DIR: docs/.vuepress/dist
#         COMMIT_MESSAGE:  Auto deploy by the vuepress-deploy
